cask_args appdir: "/Applications"
tap "caskroom/cask"
brew "ack"
brew "fasd"
brew "fzf"
brew "neovim"
brew "the_silver_searcher"
brew "tldr"
brew "tmux"
brew "reattach-to-user-namespace"
brew "tree"
brew "yarn"
brew "zsh"
brew "ranger"
brew "tig"
cask "alfred"
cask "appcleaner"
cask "itsycal"
cask "kdiff3"
cask "tunnelblick"
cask "google-chrome"
cask "parallels"
cask "slack"
cask "spotify"
cask "iterm2"
cask "bettertouchtool"
cask "karabiner-elements"
cask "visual-studio-code"
cask "postman"
cask "dropbox"
cask "textmate"
cask "transmit"
cask "docker"
cask "p4merge"
mas "Todoist", id: 585829637
mas "Amphetamine", id: 937984704
mas "SnippetsLab", id: 1006087419 
mas "Monosnap", id: 540348655
mas "Microsoft Remote Desktop", id: 1295203466
mas "iMazing HEIC Converter", id: 1292198261 
mas "iA Writer", id: 775737590
mas "Magnet", id: 441258766 
mas "Telegram", id: 747648890 
mas "SimpleMind Lite", id: 439654198 
